### ISSUE TITLE
Columns UI misbehaves on Windows XP when compiled with VS2015

### ISSUE THREAD

**Issue by msquared2** [msquared2/columns_ui#6]
This is due to some odd behaviours of static variables declared in functions in Visual C++ 2015 RTM on Windows XP, affecting some implementations of `container_window::get_class_data`.

We could either see if VC++ behaviour changes ([see report on Microsoft Connect](https://connect.microsoft.com/VisualStudio/feedback/details/1941836/visual-c-2015-static-variable-defined-within-a-function-incorrectly-initialised-on-windows-xp)), or just abandon the (admittedly funky) use of local static variables.

**Comment by msquared2** [comment]
For info, Microsoft responded on Connect.

**Comment by war59312** [comment]
Surprised you even care about XP. Let it die already. ;)

That said. If easy enough and not time consuming (ie. not a lot of effort) to fix (ie. work-around), then fine I'd go for it. Otherwise, I'd would not waste my breath. Just saying.

To each their own. Good luck. ;) Thanks for what you do. You the man! :dancers:

**Comment by msquared2** [comment]
I'm glad I'm the man ;)

I didn't care about XP support, but as it is Columns UI loads and doesn't work. Apparently, it's the same on Wine too.

Since local statics weren't thread-safe before, disabling them should be fine. Of course, there could be something else broken on XP.
